### ISSUE TITLE
Multiple packages link to native library `ring-asm`

### ISSUE THREAD

**Issue by jesdazrez** [cryptosphere/ring-pwhash#15]
Hi there:

I'm having problems building my app. When I add ring-pwhash = "0.12.0" to the Cargo.toml file and run 'cargo run' I get the following error:

    error: Multiple packages link to native library `ring-asm`. A native library can be linked only once.

    Package `ring v0.12.1`
        ... which is depended on by `ring-pwhash v0.12.0`
        ... which is depended on by `myapp v0.1.0 (file:///...)`
    links to native library `ring-asm`.

    Package `ring v0.11.0`
        ... which is depended on by `cookie v0.9.2`
        ... which is depended on by `rocket v0.3.4`
        ... which is depended on by `myapp v0.1.0 (file:///...)`
    also links to native library `ring-asm`.

I'm using rocket crate.

How can I fix this?

**Comment by tarcieri** [comment]
You either need to use `ring-pwhash` v0.11, or upgrade your app to use `ring` v0.12

**Comment by jesdazrez** [comment]
Thanks
