### ISSUE TITLE
ring-pwhash on crates.io does not build

### ISSUE THREAD

**Issue by vks** [cryptosphere/ring-pwhash#8]
This can be fixed by releasing a new version, but this is actually caused by the version requirement in the Cargo.toml. It currently says `ring = ">= 0.2"`, while newer ring versions actually break ring-pwhash. This has been fixed in 06d927e94215af6216c077d2ff05e9ad3f3ca3eb, but the fix raises the required version of ring. Hence I suggest to use `ring = "0.9"` instead and to publish a new version on crates.io.

**Comment by vks** [comment]
Thanks for merging the patch! Could you please release a new version on crates.io?

**Comment by tarcieri** [comment]
Released as v0.2.0
